### ISSUE TITLE
submodule fetch failures

### ISSUE THREAD

**Issue by hokiGit** [Goldeneye128/whonix-script#4]
great idea on the script just have a couple of issues.

Tested with Debian 12 from UTM Gallery
https://mac.getutm.app/gallery/debian-12

1.) Had to manually install apt-catcher-ng since it asks you a question in ncurses which causes the script to hang.  Maybe just have that as a requirement prior to running script.

2.) On multiple branches I am encountering submodule fetch failures.  Here is the ouput from the console log. 

```
Errors during submodule fetch:
	packages/tor-ctrl
	packages/serial-console-enable
	packages/qubes-whonix
	packages/kloak
	packages/hardened_malloc
	packages/hardened-kernel
	packages/developer-meta-files
	packages/anon-meta-packages
	kloak
	bindp
Error Report
Error 1 occurred on line 1, command: 'tee -a "${HOME}/${BL}"'

```

[build-log.tar.gz](https://github.com/Goldeneye128/whonix-script/files/14911350/build-log.tar.gz)

**Comment by Goldeneye128** [comment]
Hey i have made some fixes now on the latest commit, explanation is on the forums in details, can you test from your side if everything works fine now?

**Comment by Goldeneye128** [comment]
Well should be fixed now, make a new issue if its still a problem. Or else LGTM!
